### PR TITLE
Add next game info when there is a game for today

### PR DESCRIPTION
**Pull request by garrettgalow**
When there is a game 'today', you can't tell when the next game is. It is super useful to know, especially when the next game is the next day.

### CODE REVIEW

**Comment by lforrest** [comment]
I like it!. Let's ship it. New and improved. 

William: I can try my friend at Twitter to get access to our account. Can you confirm your email address was "williamr@mozilla.com"? (https://twitter.com/GiantsGameToday)?

**Comment by garrettgalow** [comment]
Added a fix for the location check, so now it recognizes AT&T Park substring as home.
Also didn't realize that home games changed the css so I thought I had messed up something at first.

**Comment by garrettgalow** [comment]
Updated site for today with my changes/fixes, since it is now baseball season:
http://imgur.com/a/rWp7w

**Comment by dailycavalier** [comment]
@garrettgalow many thanks for the fixes and improvements. @lforrest and I really like your idea to show the next game at the bottom of the page, and I'm sure this will be helpful for hundreds or thousands of other people too. I just published your changes on the site. Go Giants! ⚾️ 🏟

**Pull request merged**
