### PR TITLE
2018 schedule and ruby csv tweaks

### PR DESCRIPTION
**Pull request by thebrettd**
Generated a 2018 schedule and refactored the ruby CSV parser a bit

### CODE REVIEW

**Comment by thebrettd** [comment]
Oops - I need to actually test this in the UI first, but should be good 🤞. Will post back with a screenshot once this is confirmed working.

**Comment by dailycavalier** [comment]
@thebrettd thanks for submitting the new schedule and tweaks! Sounds good and I'll review after you post the screenshot.

**Comment by thebrettd** [comment]
@dailycavalier - I think we are good to go here. Here is a screenshot.

screen shot 2018-02-17 at 1 44 49 pm

I might tweak this so its says something like Friday 2/23 but this is a good start.

**Comment by thebrettd** [comment]
@dailycavalier think we can get this one merged? :)

**Comment by dailycavalier** [comment]
@thebrettd merged! I'm sorry for the delay, and thank you very much for the 2018 schedule and the ruby csv tweaks! http://isthereagiantsgametoday.com/ is now updated ⚾️

**Pull request merged**
